# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a434268f6abe0ccc0c72e8419ff3515eb821c6cadef3c45ca7ee4d210c7352d9cd4683bd6902981c5a930c5618972b3eabcaaf097d5a27b0117e1da73859b3a

test:
  secret_key_base: f84d73dba9fe972455b6b45110fa5dcc165cfe631b7c10e9f7376d56ac99cf98696d6760ed63849d9baf2c780b24edfc11acff3b0846ba7284e6d74d64e7fe2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
